# Generated by Django 4.0.1 on 2022-01-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_employee_age_alter_employee_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='User name')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
    ]
